"""Nasdaq Helsinki (OMX Helsinki) stock tickers with company names."""

HELSINKI_STOCKS = {
    "NOKIA.HE": "Nokia",
    "FORTUM.HE": "Fortum",
    "NESTE.HE": "Neste",
    "SAMPO.HE": "Sampo",
    "UPM.HE": "UPM-Kymmene",
    "STERV.HE": "Stora Enso R",
    "KNEBV.HE": "Kone",
    "OUT1V.HE": "Outokumpu",
    "WRT1V.HE": "Wartsila",
    "ELISA.HE": "Elisa",
    "TLS1V.HE": "Telia Finland (Tele2)",
    "TIETO.HE": "TietoEVRY",
    "ORNBV.HE": "Orion B",
    "ORNAV.HE": "Orion A",
    "KEMIRA.HE": "Kemira",
    "METSO.HE": "Metso",
    "NMDV.HE": "Nordic Morning",
    "HUH1V.HE": "Huhtamaki",
    "HIAB.HE": "Hiab (ex-Cargotec)",
    "METSB.HE": "Metsa Board B",
    "HKSAV.HE": "HKScan",
    "RAIVV.HE": "Raisio V",
    "KESKOB.HE": "Kesko B",
    "KESKOA.HE": "Kesko A",
    "YIT.HE": "YIT",
    "SRV1V.HE": "SRV Group",
    "ASPO.HE": "Aspo",
    "ATRAV.HE": "Atria A",
    "BIOBV.HE": "Biohit B",
    "BITTI.HE": "Bittium",
    "BOREO.HE": "Boreo",
    "CAIF.HE": "Caverion (Rexdev)",
    "CAPMAN.HE": "Capman B",
    "CTY1S.HE": "City of Tampere Bond",
    "DIGIA.HE": "Digia",
    "EFFECTS.HE": "Efecte",
    "EML1V.HE": "Empower",
    "ENENTO.HE": "Enento Group",
    "ETB1V.HE": "Etteplan",
    "EXL1V.HE": "Exel Composites",
    "FARON.HE": "Faron Pharmaceuticals",
    "FIA1S.HE": "Finnair",
    "FLRIB.HE": "Fluidra",
    "FONDIA.HE": "Fondia",
    "GOFORE.HE": "Gofore",
    "HARVIA.HE": "Harvia",
    "HRTIS.HE": "Hartwall",
    "INCAP.HE": "Incap",
    "INDAV.HE": "Indata",
    "INVE.HE": "Investors House",
    "ICP1V.HE": "Ilkka-Yhtyma",
    "KAMUX.HE": "Kamux",
    "KELAS.HE": "Kela",
    "KITRON.HE": "Kitron",
    "KOJAMO.HE": "Kojamo",  # taken private — kept for reference
    "KREATE.HE": "Kreate Group",
    "LEHTO.HE": "Lehto Group",
    "LEMON.HE": "Lemon Tree",
    "LIFA.HE": "Lifa-Air",
    "LIHAV.HE": "Lassila & Tikanoja",
    "LNWARE.HE": "Loihde",
    "MARAS.HE": "Marimekko",
    "MEKKO.HE": "Marimekko (alt)",
    "NXTMH.HE": "NextFour Group",
    "OHCBV.HE": "Olvi B",
    "OKDBV.HE": "OKO Bank",
    "OPTOMED.HE": "Optomed",
    "OVARO.HE": "Ovaro Kiinteisto",
    "PIHLIS.HE": "Pihlajalinna",
    "PKC1V.HE": "PKC Group",
    "PON1V.HE": "Ponsse",
    "PURMO.HE": "Purmo Group",
    "QTCOM.HE": "Qt Group",
    "RAUTE.HE": "Raute",
    "REKA.HE": "Reka Industrial",
    "REMEDY.HE": "Remedy Entertainment",
    "ROVIO.HE": "Rovio Entertainment",
    "RUSH.HE": "Rush Factory",
    "SCANFL.HE": "Scan AB",
    "SIEVI.HE": "Sievi Capital",
    "SOLTEQ.HE": "Solteq",
    "SPONDA.HE": "Sponda",
    "SSABAH.HE": "SSAB A",
    "SSABBH.HE": "SSAB B",
    "STTAV.HE": "Suominen",
    "TALLINK.HE": "Tallink Grupp",
    "TNOM.HE": "Tokmanni Group",
    "TTALO.HE": "Tulikivi",
    "UPONOR.HE": "Uponor",
    "VALMT.HE": "Valmet",
    "VERK.HE": "Verkkokauppa",
    "VIAFIN.HE": "Viaplay Finland",
    "VIONN.HE": "Viking Line",
    "VIK1V.HE": "Viking Line (alt)",
    "WITTOS.HE": "Wittoa",
    "XLVI.HE": "Xlvi",
    "ZEELAND.HE": "Zeeland Family",
}

# Liquid large-caps for default screener view
DEFAULT_WATCHLIST = [
    "NOKIA.HE", "FORTUM.HE", "NESTE.HE", "SAMPO.HE", "UPM.HE",
    "STERV.HE", "KNEBV.HE", "OUT1V.HE", "WRT1V.HE", "ELISA.HE",
    "TIETO.HE", "ORNBV.HE", "KEMIRA.HE", "METSO.HE", "HUH1V.HE",
    "HIAB.HE", "METSB.HE", "KESKOB.HE", "YIT.HE", "QTCOM.HE",
    "VALMT.HE", "PON1V.HE", "OVARO.HE", "KAMUX.HE", "HARVIA.HE",
]
